DATA:
  DATASET: inat21
  IMG_SIZE: 192
  BATCH_SIZE: 32
  DATA_PATH: /mnt/10tb/data/inat21/resize-192
  NUM_WORKERS: 32
AUG:
  COLOR_JITTER: 0.0
  AUTO_AUGMENT: "none"
  REPROB: 0.0
  RECOUNT: 0
  MIXUP: 0.0
  CUTMIX: 0.0
  MIXUP_PROB: 0.0
MODEL:
  TYPE: swinv2
  NAME: swinv2_large_patch4_window12_resize_192_inat21_debugging
  SWINV2:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
  # Regularization
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.0
  LABEL_SMOOTHING: 0.0
TRAIN:
  OVERFIT_BATCHES: 8
  EPOCHS: 90
  WARMUP_EPOCHS: 0
  WEIGHT_DECAY: 0.0
  BASE_LR: 1.25e-4 # 4096 batch-size
  WARMUP_LR: 1.25e-4
  MIN_LR: 1.25e-4
  HIERARCHICAL_COEFFS: [ 8, 5.65, 4, 2.82, 2, 1.41, 1 ]
  # We want N_GPU * BATCH_SIZE * ACCUMULATION_STEPS ~= 1024
  ACCUMULATION_STEPS: 4
  LR_SCHEDULER:
    NAME: "none"
HIERARHICAL: true
