DATA:
  DATASET: inat21
  IMG_SIZE: 192
  BATCH_SIZE: 32
  DATA_PATH: /mnt/10tb/data/inat21/resize-192
  NUM_WORKERS: 32
MODEL:
  TYPE: swinv2
  NAME: swinv2_large_patch4_window12_resize_192_inat21
  DROP_PATH_RATE: 0.2
  SWINV2:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.1
  BASE_LR: 1.25e-4 # 4096 batch-size
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6
  HIERARCHICAL_COEFFS: [ 8, 5.65, 4, 2.82, 2, 1.41, 1 ]
  # We want N_GPU * BATCH_SIZE * ACCUMULATION_STEPS ~= 1024
  ACCUMULATION_STEPS: 4
HIERARHICAL: true
