DATA:
  DATASET: inat21
  IMG_SIZE: 224
  BATCH_SIZE: 32
  DATA_PATH: /mnt/10tb/data/inat21/resize-224
  NUM_WORKERS: 32
MODEL:
  TYPE: swinv2
  NAME: swinv2_large_resize_224_inat21
  DROP_PATH_RATE: 0.2
  SWINV2:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 500
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.1
  BASE_LR: 1.25e-4
  WARMUP_LR: 1.25e-7
  CLIP_GRAD: 5.0
  # N_GPU * BATCH_SIZE * ACCUMULATION_STEPS = 512
  ACCUMULATION_STEPS: 2

  LR_SCHEDULER:
    NAME: constant

# Only save checkpoint every 5 epochs
SAVE_FREQ: 5

